app/__init__.py
from flask import Flask
from flask_wtf.csrf import CSRFProtect
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config


mail: Mail = Mail()
db: SQLAlchemy = SQLAlchemy()
login_manager: LoginManager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app(config_type: str="development"):
    app = Flask(__name__)

    app.config.from_object(config[config_type])
    config[config_type].init_app(app)

    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    csrf = CSRFProtect(app)


    with app.app_context():
        from .auth import auth as auth_blueprint
        from .main import main as main_blueprint
        app.register_blueprint(main_blueprint)
        app.register_blueprint(auth_blueprint)
        db.create_all()


    return app



app = create_app("production")

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import flash, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from . import main
from ..auth.models.user import User, GameRSVP, VoteAssignment
from ..auth.models.form import RSVPForm
from app.schedule.next_and_prev_game import NextGame, PrevGame
from app import db
import json


@main.route('/')
def index():
    return render_template('index.html', user=current_user)

@main.route('/next-game', methods=['GET'])
@login_required
def next_game():
    return render_template('next.html', next_game=NextGame, user=current_user)

@main.route('/votes')
@login_required
def votes():
    team: list[User] = db.session.scalars(db.select(User)).all()
    return render_template('votes.html', prev_game=PrevGame, team=team, user=current_user)


@main.route('/record-votes', methods=['POST'])
@login_required
def record_votes():
    rounds_user_voted = db.session.scalars(db.select(VoteAssignment.round).filter_by(vote_giver=current_user.id)).all()
    data: Any | None = request.json
    _, round_number = data['round'].split(' ')
    round_number = int(round_number)
    if round_number in rounds_user_voted:
        flash('You have already submitted votes for this round', 'error')
    else:
        for assignment in data['assignedVotes']:
            new_assignment: VoteAssignment = VoteAssignment()
            new_assignment.season_id = data['season']
            new_assignment.round = round_number
            new_assignment.vote_giver = current_user.id
            vote_getter = db.session.scalars(db.select(User).where(User.username==assignment['player'])).first() 
            new_assignment.vote_getter = vote_getter.id
            new_assignment.num_votes = assignment['votes']
            db.session.add(new_assignment)
            db.session.commit()

    return json.dumps({'redirect':True, 'redirectUrl': url_for('main.index')}), 302, {'ContentType':'application/json'}


@main.route('/rsvp/<round_num>', methods=['GET', 'POST'])
@login_required
def rsvp_get(round_num: str):
    form: RSVPForm = RSVPForm()

    round_text, next_round_num = NextGame.round.split(' ') # round_text = "Round", next_round_num =  "4"
    day, date = NextGame.date_str.split(' ')               # day = "Monday", date = "15/MAY/23"

    rsvp_to_this_round = db.session.scalars(db.select(GameRSVP).filter_by(user_id=current_user.id, game_date=date)).first() 
    
    if rsvp_to_this_round and request.method == 'GET':
        prev_response = "PLAYING" if rsvp_to_this_round.is_playing else "NOT PLAYING"
        flash('You have already provided a response. Please be aware you are now updating your previous answer.', 'error')
        return render_template('rsvp.html', user=current_user, next_game=NextGame, form=form, rsvp=rsvp_to_this_round, prev_response=prev_response)
    elif rsvp_to_this_round and form.validate_on_submit():
        player_response = True if form.availability.data == 'True' else False
        rsvp_to_this_round.is_playing = player_response
        db.session.commit()
        flash('Thank you for updating your RSVP!', 'success')
        return redirect(url_for('main.index'))

    rsvp: GameRSVP = GameRSVP()
    
    if request.method == 'GET' and next_round_num == round_num:
        return render_template('rsvp.html', user=current_user, next_game=NextGame, form=form, rsvp=rsvp)
    elif form.validate_on_submit():
        rsvp.game_date = date
        rsvp.user_id = current_user.id
        player_response = True if form.availability.data == 'True' else False
        rsvp.is_playing = player_response
        db.session.add(rsvp)
        db.session.commit()
        flash('Thanks for RSVPing -- your team mates appreciate it!', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('RSVP link invalid or expired. Are you sure this game has not already been played?', 'error')
        return redirect(url_for('main.index'))


@main.route('/my-availability', methods=['POST'])
@login_required
def rsvp_post():
    data = request.get_json() if request.is_json else None
    if not data:
        raise ValueError('No JSON data in POST request')
    

    return json.dumps({'redirect':True, 'redirectUrl': url_for('main.index')}), 302, {'ContentType':'application/json'}

app/templates/base.html
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="{{ url_for('static', filename='js/main.js') }}" type="text/javascript"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

  {% block scripts %} {% endblock scripts %}
</head>



{% block navbar %}



<nav class="w-full bg-black border-b-2 border-gray-500 text-lg" id="navbar">
  <div class="container md:flex md:flex-wrap md:items-center md:justify-between md:mx-auto">

  

  <div class="flex justify-center text-white font-bold py-4">
    SharksApp - {% block title %} SharksApp {% endblock %} 
  </div>


  <div class="flex flex-wrap justify-between mx-4">

  <a class="text-white" href={{ url_for('main.index') }}>
      <button class="hover:bg-slate-500 p-4 my-2 rounded-md">
          Home
      </button>
      </a>

      <a class="text-white" href={{ url_for('main.votes') }}>
    <button class="hover:bg-slate-500 p-4 my-2 rounded-md">
          Votes
  </button>
  </a>

  <a class="text-white" href={{ url_for('main.next_game') }}>
    <button class="hover:bg-slate-500 p-4 my-2 rounded-md">
          Next game
  </button>
  </a>


  {% if user and user.is_authenticated %}
 <a class="text-white" href={{ url_for('auth.my_profile') }}>
    <button class="hover:bg-slate-500 p-4 my-2 rounded-md">
          My Profile
  </button>
  </a>


  <a class="text-white" href={{ url_for('auth.logout') }}>
  <button class="hover:bg-slate-500 p-4 my-2 rounded-md">
      Logout
    </button> 
    </a>

{% else %}
<a class="text-white" href={{ url_for('auth.login') }}>
    <button class="hover:bg-slate-500 p-4 my-2 rounded-md">
      Login
    </button> 
    </a>
{% endif %}

  </div>
    </div>
  </nav>

{% endblock %} {% block content %}

<div class="">
  {% with messages = get_flashed_messages(with_categories=true) %} {% if
  messages %} {% for category, message in messages %} {% if category ==
  'success' %}

  <div id="flash_message" class="max-w-screen-sm bg-green-100 border-2 border-green-200 flex justify-between p-4 my-2 mx-auto rounded" role="alert">
    {{message}} 
    <button type="button" onclick="removeFlash()">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  {% else %}

  <div id="flash_message" class="max-w-screen-sm bg-yellow-100 border-2 border-yellow-200 flex justify-between p-4 my-2 mx-auto rounded" role="alert">
    {{message}}
    <button type="button" onclick="removeFlash()">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  {% endif %} {% endfor %} {% endif %} {% endwith %} {% block page_content %}{%
  endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% block title %} Home {% endblock %} {% block
page_content %}
<div class="flex h-96">
  <img
    class="m-auto"
    src="{{url_for('static', filename='images/sharks-logo.webp')}}"
  />
</div>
{% endblock%}
<!-- Add ability to post words of encouragement here side by side with comments from last game -->

app/templates/next.html
{% extends "base.html" %} {% block title %} Next game {% endblock %} {% block
page_content %}
<div class="flex justify-center">
  <div>
    <h1 class="text-3xl font-bold my-4">Next Game</h1>
    <ul class="my-2 text-lg">
      <li>{{ next_game.round }}</li>
      <li>{{ next_game.date_str }}</li>
      <li>{{ next_game.time_str }}</li>
      <li>{{ next_game.teams }}</li>
      <li>{{ next_game.location }}</li>
    </ul>
  </div>
</div>
{% endblock %}

app/templates/rsvp.html
{% extends "base.html" %} {% block scripts %}

{% endblock scripts %} {% block title %} Availability {% endblock title %} {% block
page_content %}

<div class="flex justify-center">
  <div>
    <h1 class="text-3xl font-bold my-4">Confirming your availability for {{ next_game.round }}</h1>
    <ul class="my-2 text-lg">
      <li>{{ next_game.date_str }}</li>
      <li>{{ next_game.time_str }}</li>
      <li>{{ next_game.teams }}</li>
    </ul>
    {% if prev_response %}
    <div class="font-bold mt-4">
      You previously said you were {{ prev_response }}
    </div>
    {% endif %}
  </div>
</div>

<form method="POST" autocomplete="off" class="space-y-4">
  {{ form.csrf_token }} 
  <div class="flex">
  {{ form.availability(class_="mx-auto", value=rsvp.is_playing) }} 
  </div>
  <div>  
      <button class="flex mt-4 bg-blue-300 border-2 border-blue-400 p-2 rounded mx-auto hover:bg-blue-200">
        {{ form.submit(class_="hover:cursorpointer")  }}
      </button>
  </div>
</form>
{% endblock page_content %}

app/templates/votes.html
{% extends "base.html" %} {% block scripts %}

<script src="
https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.all.min.js
"></script>

<script
  type="text/javascript"
  src="{{ url_for('static', filename='js/votes.js') }}"
></script>

{% endblock scripts %} {% block title %} Votes {% endblock title %} {% block
page_content %}

<div class="flex justify-center">
  <div>
    <h1 class="text-3xl font-bold my-4">Votes for {{ prev_game.round }}</h1>
    <ul class="my-2 text-lg">
      <li>{{ prev_game.date_str }}</li>
      <li>{{ prev_game.time_str }}</li>
      <li>{{ prev_game.teams }}</li>
    </ul>
  </div>
</div>

<form class="p-24 mx-auto space-y-8">
  <input type="hidden" id="csrf_token" value="{{ csrf_token() }}"/>
  <div class="flex justify-between">
    <div class="">
      <label for="player">Player</label>
      <select id="playerMenu1" class="">
        <option selected></option>
        {% for player in team %}
        <option>{{ player.username }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="">
      <label for="votes"> Votes </label>
      <select id="votesMenu1" class="">
        <option selected></option>
        {% for i in range(1, 4) %}
        <option>{{ i }}</option>
        {% endfor %}
      </select>
    </div>
  </div>

  <hr />

  <div class="flex justify-between">
    <div class="">
      <label for="player">Player</label>

      <select id="playerMenu2" class="">
        <option selected></option>
        {% for player in team %}
        <option>{{ player.username }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="">
      <label for="votes"> Votes </label>
      <select id="votesMenu2" class="">
        <option selected></option>
        {% for i in range(1, 4) %}
        <option>{{ i }}</option>
        {% endfor %}
      </select>
    </div>
  </div>

  <hr />

  <div class="flex justify-between">
    <div class="">
      <label for="player">Player</label>

      <select id="playerMenu3" class="">
        <option selected></option>
        {% for player in team %}
        <option>{{ player.username }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="">
      <label for="votes"> Votes </label>
      <select id="votesMenu3" class="">
        <option selected></option>
        {% for i in range(1, 4) %}
        <option>{{ i }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
</form>

<div class="mb-12">
  <button
    class="flex bg-blue-300 border-2 border-blue-400 p-2 rounded mx-auto hover:bg-blue-200"
    onclick="submitVotes('{{prev_game.season_id}}','{{prev_game.round}}', '{{prev_game.date_str}}')"
  >
    Submit votes
  </button>
</div>

{% endblock page_content %}